### ISSUE TITLE
NAND memory decode error

### ISSUE THREAD

**Issue by KenWillmott** [TheEccentricGenius/HD6303RP_EVB#2]
Here, E is inverted with a gate, and R/W goes to both final NANDs:
![image](https://github.com/TheEccentricGenius/HD6303RP_EVB/assets/17345651/e382d4ca-04aa-4b35-8fcb-b4a3197acdd7)
That's not correct, it's reversed, R/W should be inverted, as:
![image](https://github.com/TheEccentricGenius/HD6303RP_EVB/assets/17345651/5851a364-f537-4ab0-bc6e-093d3d0ac470)

**Comment by TheEccentricGenius** [comment]
Thanks, I didn't see that....I should've paid closer attention.

**Comment by TheEccentricGenius** [comment]
I have fixed and updated the schematic.
